### ISSUE TITLE
KA-Block! does not have the permission...

### ISSUE THREAD

**Issue by daslicht** [dgraham/Ka-Block#100]
Hi,
I just installed Ka-Block from teh new Appstore in MacOs Mojave,
when I enable the extension in Safari I get, and nothing is blcoked:
![](https://i.imgur.com/6u2F8Fo.png)

How to fix ?
~Marc

**Comment by dgraham** [comment]
This is a feature! The content blocking extension simply provides Safari with a list of domains to block and does not run while you browse. The extension has no knowledge of the sites you visit or the content of pages you view.

Look for this message in other browser extensions to verify they aren't tracking your browsing history.

**Comment by daslicht** [comment]
ahh i see, is there a way to add custom blocked urs without posting a pull request each time ?
how aount just selecting an element to block like it was (ius possible with other browsers) possible with other blockers before ?

**Comment by dgraham** [comment]
Bundling the block list with the app means it never [contacts a server](https://github.com/dgraham/Ka-Block#there-must-be-a-better-way), so there's no way for it to collect data about users. Either a pull request or just an issue with new domains to block, and the sites on which they appear, would be fine.

**Comment by daslicht** [comment]
The serverless integration is great but I'd rather like to add a local config and do not have to send a pull request each time. On the other hand if I post a pull request anyone will see that in public here as well. So selectively blocking elements on a page isn't possible either like it is for example possible with uBlock Origin for FireFox?

**Comment by dgraham** [comment]
> So selectively blocking elements on a page isn't possible 

Right, this extension is designed to require zero configuration. Just install it and it works. Those other content blockers are great too.

**Comment by dgraham** [comment]
We disabled that block in #22 because the videos wouldn't play. It's possible the video player works in a way that would allow blocking them now, though.
