### ISSUE TITLE
block list additions

### ISSUE THREAD

**Issue by core-code** [dgraham/Ka-Block#104]
hey,

i've got a list of domains i want blocked because they serve ads. can you either add them or add a way to add your own blocklist to Ka-Block?

thanks
[blocklistsource.txt](https://github.com/dgraham/Ka-Block/files/2445540/blocklistsource.txt)

**Comment by TjOsT1975** [comment]
Please a whitelist

**Comment by dgraham** [comment]
A pull request that adds behavioral tracking/advertising domains and a link to the sites that use it is welcome. We don't import large lists of domains so the block list stays curated and fast.

Safari has a built-in whitelist feature that allows disabling content blocking extensions per site.
