### ISSUE TITLE
Explain how ka-block makes money

### ISSUE THREAD

**Issue by fulldecent** [dgraham/Ka-Block#106]
I tell everyone

* Delete all your browser extensions because they are spying on you, that's how they make money
* Install Ka-block browser extension

It will be helpful if Ka-Block better explains its motivation and how development effort is funded.

**Comment by dgraham** [comment]
We don't! We work on Ka-Block! in our free time and don't make money from it.

It's a free app in the iOS and Mac app stores and it's [open source](https://github.com/dgraham/Ka-Block/blob/master/LICENSE). You can modify the source code to build your own extension or inspect it to see what's actually running on your device.

When Safari introduced an extension mechanism I wondered how it worked and if I could use it to make an ad blocking extension that doesn't track its users. Curiosity and privacy were really my only motivations.
