### ISSUE TITLE
Paypal.com slipped through the cracks

### ISSUE THREAD

**Issue by fulldecent** [dgraham/Ka-Block#108]
Huge click-through ads when you login and then after you login.

As if logging in and spending money with them was not enough.

**Comment by dgraham** [comment]
The filter list is intended to block third-party domains that collect information on visitors to build a unique profile across websites. First-party content, like ads served directly from PayPal.com, isn't blocked.

I don't currently see any third-party domains serving ads on PayPal. If you spot one, we can add it to the filter list.
