### ISSUE TITLE
Whitelist qualtrics.com subdomains

### ISSUE THREAD

**Issue by acrostich** [dgraham/Ka-Block#112]
Many universities use Qualtrics for research surveys. These are usually (always?) hosted on a subdomain of qualtrics.com. As the whitelisting in Safari is only for a specific site, it is inconvenient to have to whitelist all the universities subdomains when participating in several research projects so this would be better handled by Ka-Block.

Here's an example of an URL used: https://edinburgh.eu.qualtrics.com/jfe/form/<code for a specific survey>

**Comment by dgraham** [comment]
This domain is blocked because it performs behavioral tracking across sites via third-party scripts. Disabling the content blocker for this domain and its subdomains in Safari is the best option.
