### ISSUE TITLE
At chance of iPhone 5 support?

### ISSUE THREAD

**Issue by stig** [dgraham/Ka-Block#12]

**Comment by ncrow** [comment]
@stig the content blocking API that Kablock (and all the other iOS content blockers) is 64 bit only.   So no iPhone 5.

**Comment by dgraham** [comment]
iPhone 5S is the oldest model that supports the content blocking feature of iOS 9.

**Comment by stig** [comment]
Ah, that explains it. I thought I could manage to get one more year out of this phone but this might me upgrade…

Stig
