### ISSUE TITLE
Does not work with managed Mac accounts

### ISSUE THREAD

**Issue by markobuuri** [dgraham/Ka-Block#126]
On managed Mac accounts the app says blocking is enabled and everything is fine. Yet the extension does not appear of Safari's list of extensions and the blocking is actually not in effect.

I have experienced this on Mojave and can not figure out how to solve. Reinstalling the app does not fix this.

I have made sure that parental controls allow running Ka-Block app.

**Comment by dgraham** [comment]
I'm not really familiar with managed user accounts, so I'm not sure I can help here. There's nothing in the Ka-Block! app that deals with user permissions, so it's likely a macOS configuration issue.
