### ISSUE TITLE
Application size

### ISSUE THREAD

**Issue by josh** [dgraham/Ka-Block#13]
Since Ka-Block is planning to ship all block list updates over the air, it'd be great if our app binary was super tiny.

## App Size comparisons

![](https://cloud.githubusercontent.com/assets/137/10119352/a8649baa-6448-11e5-8326-05e15b4652b6.jpg)

**Ka-Block 2.2**

App Size: 5.9 MB
Documents & Data: 340 KB

**Peace 1.0**

App Size: 1.4 MB
Documents & Data: 92 KB

**Crystal 1.0.1**

App Size: 7.8 MB
Documents & Data: 860 KB

**1Blocker 1.0**

App Size: 10.1 MB
Documents & Data: 1.7 MB

**Purify 1.0.1**

App Size: 21.3 MB
Documents & Data: 76 KB

## Ideas

* [ ] Research iOS 9 "App Thinning" (Slicing, Bitcode)
* [ ] Research generating logo from vector code (PaintCode)
* [ ] Research other ways to reduce the size of *AppIcon.appiconset* and *Home.appiconset*
* [ ] Research what "Documents & Data" is being used for. Ka-Block doesn't have any user settings right now.

-
To: @dgraham

**Comment by floam** [comment]
Going to guess Peace may be the only one on that list that's just obj-c. Ka-Block's ipa is mostly a Swift runtime.

**Comment by dgraham** [comment]
App Slicing [is delayed](https://developer.apple.com/news/?id=092415a&1443125762) right now. It will be interesting to check the installed app size after that feature ships. We might be able to improve before then:

![screen shot 2015-09-26 at 18 37 10](https://cloud.githubusercontent.com/assets/122102/10120554/b13e1e24-647d-11e5-9af1-ff440422049f.png)

I just dragged and dropped an app icon image onto every spot, not knowing how these settings are used. Most of these sizes are for versions of iOS, and devices pre-5S, that can't even install or run the app. Maybe we can delete those and the app would still work fine in iOS 9 and above.



> Ka-Block's ipa is mostly a Swift runtime.

We should expect this runtime to be included in iOS itself eventually, right? We could rewrite in Objective-C or wait for iOS 10 to include the Swift runtime for us.

**Comment by josh** [comment]
> We could rewrite in Objective-C or wait for iOS 10 to include the Swift runtime for us.

Alright, we can 🏈 on this and wait and see what iOS 10 does.

**Comment by dgraham** [comment]
Ka-Block! version 2.4 is down to 1.6 MB on iOS 9.1. This is the first app update we've shipped since Apple enabled the app thinning feature.

**Comment by josh** [comment]
🌭
