### ISSUE TITLE
Update for MacOS and iOS apps?

### ISSUE THREAD

**Issue by abhayap** [dgraham/Ka-Block#136]
Hi @dgraham,
I love this extension. Any chance we can get a new release for Mac and iOS with all the latest commits?
Thanks!
Abhaya

**Comment by VadimMuhtarov** [comment]
Update your app please

**Comment by dgraham** [comment]
I fixed a couple issues that caused the macOS app to be rejected and version 3.3 is in the App Store now.

**Comment by abhayap** [comment]
Thanks!
