### ISSUE TITLE
Minimize rule set

### ISSUE THREAD

**Issue by josh** [dgraham/Ka-Block#14]
Ka-Block's current block list is tiny compared to other apps. Ka-Block 2.2 shipped with 278 rules. And I think this is great, we should focus on a small optimized list.

I haven't done any measurements myself, but supposedly larger lists take more time to compile and load into the memory. This impacts the speed of the "Reload without Content Blockers" action.

Should we set an informal goal somewhere that we plan to stay under 500/1,000/2,000 rules?

## Resources

* "Ghostery blocked more trackers and had fewer compatibility problems, with a reasonably sized blocklist of about 2,000 entries." - http://www.marco.org/2015/09/16/peace-content-blocker
* *Uncomfortable in My Pants* Post-show http://atp.fm/episodes/135

-
To: @dgraham

**Comment by dgraham** [comment]
> I think this is great, we should focus on a small optimized list.

Me too. Our hand-built, optimized list of domains, actively serving behavioral tracking scripts and images, is one of our best features! Really, it's our only feature.

> Should we set an informal goal somewhere that we plan to stay under 500/1,000/2,000 rules?

Yes, and we could actually do better with our current rule set. The current rules match *all* subdomains even though many trackers have only a few known subdomains. For example, this

    ^https?:/+([^/:]+\\.)?google-analytics\\.com[:/]

could be simplified to

    ^https?://www\\.google-analytics\\.com[:/]

The danger is that the subdomain changes, or is randomly generated, and we have to update the block list. For it to be worthwhile, we need a way to compare performance after regex changes. If it's not much faster, the safer subdomain glob is easier to manage.

It might be fun to be part of this comparison: https://brooksreview.net/2015/09/content-blocker-test/

**Comment by josh** [comment]
Cool, I feel like we agree on keeping a small optimized list. No action to be done right now.
