### ISSUE TITLE
Unable to login due to content blocker

### ISSUE THREAD

**Issue by redvivi** [dgraham/Ka-Block#148]
System: Safari 13.1.2 on macOS 10.13.6, Ka-Block 3.3.

Steps to reproduce:
1. Activate Ka-Block
2. Go to Smartlook.com
3. Try to login
4. Unable to login due to content blocker

Console output
![image](https://user-images.githubusercontent.com/50769797/99228711-44cdc300-27ed-11eb-922e-4a69f07adad2.png)

**Comment by dgraham** [comment]
This domain was blocked in 945df91e for being a key logger or mouse movement behavioral tracking script.
