### ISSUE TITLE
Performance simulation script

### ISSUE THREAD

**Issue by josh** [dgraham/Ka-Block#15]
I had a half baked idea to wrote on a PhantomJS script that'd measure a web page's load time and external resource stats without blocking and then with a JS implementation running our block list. This might help automate the stats on the gh-pages marketing page and help us evaluate the impact of future changes to the block list.

-
To: @dgraham

**Comment by dgraham** [comment]
> This might help automate the stats on the gh-pages marketing page

This took a long time to do manually: collect the before and after data on a dozen sites, select a few to be included in the graph, normalize the gathered values to the y-axis height, and add the CSS rules.

I didn't anticipate refreshing the site too often, but a script would allow for it.

**Comment by josh** [comment]
> I didn't anticipate refreshing the site too often

Well then, not a problem! 😁
