### ISSUE TITLE
Integrate cookie consent blocking

### ISSUE THREAD

**Issue by sebastianlohmann** [dgraham/Ka-Block#151]
Ka-Block is currently not considering cookie consent blocking as e.g. [Prebake](http://prebake.eu) and others do. It'd be really great to integrate cookie consent blocking as well!

**Comment by harripj** [comment]
+1 for this, or at least the option to implement it.

**Comment by jrdnrch** [comment]
There is a GNU licensed list provided by the author of the[ I don't care about cookies](https://www.i-dont-care-about-cookies.eu) extension here: https://www.i-dont-care-about-cookies.eu/abp/

I'm not sure the technical debt it would take to implement this to Ka-Block I'm guess one would have to parse this cookie consent block list to json in the proper format for blockerList.json.  

or would it call for an entirely new file to also be checked for the Safariextension?

or would there be a way we could "If one so desires" upload this list to a file directory within this plugin locally? 

I'm not a coder, so its all speculation please go easy on me if I'm totally out of bounds on what I'm talking about.

**Comment by dgraham** [comment]
I've been using [Hush](https://github.com/oblador/hush), along with Ka-Block!, and it's been working well. Each extension can focus on its strengths: Ka-Block! for tracking scripts and Hush for "this website uses cookies" banners.

**Comment by jrdnrch** [comment]
@dgraham  Excellenl find! I had no idea that existed. Thanks so much.
