### ISSUE TITLE
Whitelisting option?

### ISSUE THREAD

**Issue by mcvendrell** [dgraham/Ka-Block#154]
Hi. 

I saw that there was a previous petition for Whitelisting on OSX, denied because you can do it in the Safari options.

But what about iOS? I do not see any practical option on iOS to let some websites to load without Ka-Block. The only way is to go to Settings->Safari->Blockers, disable it, go to Safari, reload the page, then do all steps again to activate it.

Would be nice if you can add an option to do a whitelist, just like "Better" do (https://source.ind.ie/better/app).
Maybe you can even see how they actually do and replicate it.

**Comment by jrdnrch** [comment]
@mcvendrell For iOS it is a similar way to whitelist specific sites as on MacOS. One has to click the aA icon in the address bar to see the 2 different options. 
1. **Turn off Content Blockers**- this will turn it off for _only_ that web page, for that specific browser session only. If you refresh or navigate away the blocker will be turn back on automatically. 
2. **Website Settings** - this will allow you to turn it off for that specific site you are on at the moment going forward. If you wish to enable content blockers for that site again, you have to click website settings again and enabled it. 

Make sure that under Settings > safari > Content Blockers > Ka-Block is _enabled_ in order for the above mentioned methods to work. This way, one does not have to navigate to settings every single time to enabled and disable. 

Check out the screenshots below to help

![IMG_3C0FD3701D8A-1](https://user-images.githubusercontent.com/3683251/117017485-a0b7d580-acc1-11eb-9514-11e44ee21882.jpeg)
![IMG_DD804A05373F-1](https://user-images.githubusercontent.com/3683251/117018175-44a18100-acc2-11eb-958a-715d3d51b65c.jpeg)


As far as I know there isn't a way to import a list of sites and have them white-listed but you can edit status for existing white-listed sites as seen in the screenshot. You just have to do it one by one as you navigate to sites.

Hope this helps.

**Comment by mcvendrell** [comment]
> @mcvendrell For iOS it is a similar way to whitelist specific sites as on MacOS. One has to click the aA icon in the address bar to see the 2 different options.
> 
> 1. **Turn off Content Blockers**- this will turn it off for _only_ that web page, for that specific browser session only. If you refresh or navigate away the blocker will be turn back on automatically.
> 2. **Website Settings** - this will allow you to turn it off for that specific site you are on at the moment going forward. If you wish to enable content blockers for that site again, you have to click website settings again and enabled it.
...
> Hope this helps.

Amazing response. Thank you very much, @jrdnrch. I usually forget that "aA options" because I never use it. I tried it and works perfectly. Maybe would be useful to add this info to the main page. I can do it if you want (I'm good doing "user manuals").

**Comment by jrdnrch** [comment]
@mcvendrell you're more than welcome sir. You're right, a light wiki could be useful. Maybe the repo owner can enable wiki.

**Comment by mcvendrell** [comment]
I sent yesterday a pull request with that info on the README.MD file.
Simply waiting for approval.

**Comment by jrdnrch** [comment]
@mcvendrell ahh good idea.
