### ISSUE TITLE
Blocking video ads in El Capitan Safari

### ISSUE THREAD

**Issue by tonycoco** [dgraham/Ka-Block#18]
Any way to block the video ads from ESPN and Wired?

**Comment by tonycoco** [comment]
@josh @dgraham can we start a "this isn't blocked" list?

**Comment by RnbWd** [comment]
have they depreciated the extension API for older browsers? I haven't seen any hybrid content blockers with javascript to fire events to indicate an ad loaded. I've found workarounds with user scripts like https://github.com/YePpHa/YouTubeCenter but it only applies to youtube. Every safari is introducing changes and  I just read 9.0.2 gives you the option to refresh without a content blocker like in iOS

**Comment by dgraham** [comment]
> Note: The onbeforeload event and canLoad message for content blocking have been deprecated.
— [Safari 9 release notes](https://developer.apple.com/library/prerelease/ios/releasenotes/General/WhatsNewInSafari/Articles/Safari_9.html)

The Content Blocking feature replaced the synchronous `canLoad` event that blocks the event loop while it runs.

**Comment by dgraham** [comment]
> Any way to block the video ads from ESPN and Wired?

The ads are embedded in the video stream specifically to [avoid ad blockers](https://www.brightcove.com/en/once).
