### ISSUE TITLE
Any possibility of getting a version that works on Safari 12 (Sierra)

### ISSUE THREAD

**Issue by Bromaynard** [dgraham/Ka-Block#181]
I just found this extension and it works fantastic on my newer Laptop, but I have 2 older Macs I am not able to upgrade MacOS on due to hardware constraints, but I desperately need this extension when I update plugins, and software on a audio workstation and MacMini plugged into a TV.  Is there an older version I can install on MacOS 10.12.6/Safari 12.1.2?  Thanks.

**Comment by dgraham** [comment]
You might be able to build an older version of the code and run it on Sierra. We only officially support macOS versions that Apple supports, though.
