### ISSUE TITLE
A possibility given this curated, short domain list: system-wide analytics blocking. 

### ISSUE THREAD

**Issue by floam** [dgraham/Ka-Block#19]
One property this curated list of domains has is that for the most part it's a hosts-file block. With the new WebKit extension this list will benefit from some richer and more narrowly-defined rules over time but in a etc/hosts it's all good. 

There is one effective way to pull off a hosts blocking that I know of in iOS (Maybe more now with the new Network Extension Points in iOS 9?). It's unfortunately named "adblock" and hard to search for, I'm referring to this guy: http://adblockios.com/faq/. It's from the "wedlock" guy who had that WiFi-only solution.

I once bought it for kicks and it's kind of clever. His app is just a shim that points Safari at hosted .mobiconfig to download and for the user to install that he keeps updated. It defines a "Dummy" On-Demand VPN at 127.0.0.1:31337, on-demand just for the ad servers such that any attempt to reach them will try to take that path and fail. Able to block in-app ads and analytics system-wide, on WiFi and cellular. I tried it out and it worked. Very surprised Apple's OK with it as it gets iAds too, I figured that's suicide.

Ever put thought into doing something like this with an even further pared down list for in-app trackers & serious funny business?

Worst deal with his way is making users install this profile they don't understand and it would require your app remove that for them if they don't know how themselves and then they're stuck if they just remove your app and don't know about the profile left behind.

My real thoughts are on Network Extension Points. Could be done very cleanly with these. I can't find much any projects even talking about using those to protect privacy except shadowsocks. Apple did grant them the special entitlements necessary to use the Network Extension Points. Would they for an in-app ad blocker network extension? I doubt it, but a tracker-only one? I think maybe.

**Comment by floam** [comment]
And wow, there's another one on the App Store called '"Adblock Mobile" (adbl0ck.com)  and it looks like it actually sets up a real VPN to the dude's server and the privacy policy says they sell the data gleaned to  market researchers in their privacy policy. Jeez.

**Comment by dgraham** [comment]
Nice, I didn't realize that was possible on iOS. Ka-Block! is only designed for Safari content blocking, though. Other apps can specialize in network level techniques—it's just outside the scope of this app.
