### ISSUE TITLE
Some ads are not blocked

### ISSUE THREAD

**Issue by heubergen** [dgraham/Ka-Block#21]
Hi

I use the safari extension of Ka-Block and theres some sites where I still can see ads.

URL: http://www.toppreise.ch/index.php?search=beats+by+dre+solo&sRes=OK
Image: http://image.z33.ch/toppreise.png

URL: http://www.watson.ch
Image: http://image.z33.ch/watson.png

URL: http://jpgames-forum.de/jpgames-de-foren/news-rund-um-japanische-videospiele/40925-supermassive-games-denkt-über-until-dawn-2-nach/
Image: http://image.z33.ch/jpgames.png

URL: http://www.flashscore.de/eishockey/schweiz/
Image: http://image.z33.ch/flashscore.png
Note: The dashed line are social media buttons, but I'm not sure if you want to block them at all.

URL: http://t3n.de
Image: http://image.z33.ch/t3n.png

I made screenshots and mark what I mean because the sites are in german.

Hope you can fix that.

**Comment by dgraham** [comment]
The empty space on t3n.de is expected. The content is blocked and the space in which it would appear is still reserved.
