### ISSUE TITLE
YouTube videos do not start immediately

### ISSUE THREAD

**Issue by heubergen** [dgraham/Ka-Block#22]
When I click to a yt video like https://www.youtube.com/watch?v=PTh1Q2v-eIc the video doesn't start immediately like "normal" (without this addon). It's waiting around 5 seconds.

**Comment by dgraham** [comment]
The delay seems to correlate with the "Skip this ad in 5 seconds" countdown that appears with content blocking disabled. I'm not sure that can be avoided with a content blocker list, though.

**Comment by josh** [comment]
Having the same issue here. Though, often the video just never starts playing. Its more annoying on desktop since theres no "Refresh without Content Blockers" button.

>  I'm not sure that can be avoided with a content blocker list, though.

We could whitelist the rule on the youtube domain.

**Comment by tbnv** [comment]
Same here, some YouTube videos never play (on YouTube or embedded). It's a bit annoying… :disappointed: Still nothing feasible about that?

**Comment by dgraham** [comment]
Fixed in 789fc7444e9bd334d7f99b867f793f00933941dd.
