### ISSUE TITLE
Whitelisting and other config options for Ka-Block on OS X?

### ISSUE THREAD

**Issue by stukey** [dgraham/Ka-Block#25]
Hi guys,

Any chance you can add whitelisting functionality to the OS X version of Ka-Block? Currently it seems like none of the OS X content blockers allow any kind of customisation or configuration. I'd like to white-list my favourite sites that don't use offensive ads. Also I'd like to see control of ad blocking vs. tracking vs social media blocking, etc. The content blockers on iOS seem to offer a lot more configuration options... Are these things just not possible under OS X?

Thanks!

**Comment by keenam** [comment]
+1
One blocker on the GitHub that I'm aware of has in its TODO:
"Modify, recompile JSON rules in app".

A great feature suggestion for Ka-Block.

**Comment by dgraham** [comment]
> Any chance you can add whitelisting functionality to the OS X version of Ka-Block?

This is unlikely to be added because few people would use it.

We need to describe the conditions required for removal from the block list, like not setting cookies or tracking query parameters and supporting Do Not Track headers. An ad passing through the content blocker because it respects the visitor's privacy is a better way to support our favorite sites, and it avoids requiring people to customize the extension themselves.

> Also I'd like to see control of ad blocking vs. tracking vs social media blocking, etc.

We are discussing blocking categories in #16.

> Are these things just not possible under OS X?

Safari supports extension preferences that would allow customization. It also supports loading a block list programmatically, so the extension can build rules based on these preference settings.

**Comment by kfix** [comment]
> This is unlikely to be added because few people would use it.  

Uhm, I'd use it!

>  An ad passing through the content blocker because it respects the visitor's privacy is a better way to support our favorite sites, and it avoids requiring people to customize the extension themselves.  

Maybe so, but everyone has different favorite websites. Do you really intend to support them all?
I agree with nudging towards incentivizing site owners to get mainlined into *artisinal* blockers, but a barebones whitelist is invaluable for debugging and experimentation.
A decent alternative is a toolbar/context-menu mounted enable/disable button.

**Comment by stukey** [comment]
I'd use the white-listing options too - that's why I asked for them. I already have multiple sites white-listed in my iOS ad-blocker. There are some sites that just break with a content blocker enabled. I would like to be able to white-list those sites rather than having to go to Safari, Preferences, Extensions and disabling and enabling Ka-Block when needed. Maybe you could add a toolbar button that enables you to enable/disable Ka-Block? That would at least help.

Example site that breaks with Ka-Block enabled - Virgin Media TV Anywhere: http://anywhere.virginmedia.com

**Comment by kfix** [comment]
If you enable the Develop menu in Safari, there's a Disable Extensions menu item in there. a little faster than the Preferences -> Extensions dance.

**Comment by dgileadi** [comment]
I know this is closed, but here's my vote for a reopen: as others have said, there are some sites that don't work with the default blocks. There are also some occasions where I'd like to support particular sites by permitting ads. These are reasons why I'd love a whitelist.

**Comment by CaioBianchi** [comment]
Can we revisit this? 1Blocker for Mac has it.

**Comment by skisulli** [comment]
I agree, not only do some sites break with blockers on, as a web developer, I need to disable blocking for the sites I work on.

**Comment by Forox** [comment]
Whitelisting specific sites is a MUST-have feature as sites increasingly block blockers ==> uninstalled Ka-Block and installed 1Blocker instead, thanks for the tip!

**Comment by danieldickison** [comment]
I've found this less of an issue once I learned of the long-click/tap on the reload button to "Reload Without Content Blockers" option.

**Comment by stukey** [comment]
I've switched to 1Blocker too. It has all the features you need to whitelist sites and report broken sites, as well as syncing via iCloud between Mac and iOS.

**Comment by jtmkrueger** [comment]
As a developer, I need to be able to turn blockers off for localhost. Clients don't always have the same privacy concerns and values I do, so I need to be able to not have this be an issue on their sites. I get this isn't a majority of users issue, but I think worth adding to the conversation here.

**Comment by dgraham** [comment]
> I need to be able to turn blockers off for localhost

Content blocking can be configured per-site at Safari > Preferences > Websites > Content Blockers.
