### ISSUE TITLE
some devour.com videos don't load

### ISSUE THREAD

**Issue by mschrag** [dgraham/Ka-Block#26]
Here's an example of one: http://devour.com/video/david-spade-reveals-the-origins-of-fat-guy-in-a-little-coat/

With the blocker on, I get a black video area, but nothing playing. With the blocker off, it works properly (but with an ad). The latest version is an improvement over the one from a couple weeks ago where it wouldn't even give me the black video area, btw.

**Comment by dgraham** [comment]
Interesting, the behavior I'm seeing is a 15 second pause before the video starts. It's waiting for the ad to finish playing, but the ad video was blocked from loading. Does the video just not start at all for you?

If this is the desktop Safari extension, make sure you [download the latest version](https://github.com/dgraham/Ka-Block/releases/latest). I'm not sure when Apple will approve the version updates in their extension gallery.

**Comment by mschrag** [comment]
Interesting. The first time, it was just a black screen that never loaded. Now I'm seeing the 15 second pause. Maybe it was just a fluke. This was the latest build, btw. I'll close this and re-open if I see it again.
