### ISSUE TITLE
Compability with Adblock

### ISSUE THREAD

**Issue by demidovakatya** [dgraham/Ka-Block#27]
Is Ka-Block compatible with [Adblock](https://getadblock.com)? With TrafficLight? With Ghostery (and any other security extension for OS X Safari)?

**Comment by dgraham** [comment]
Safari evaluates content blocking rules from all enabled extensions. If one block list misses something, the next extension has the opportunity to block it. Each extension adds a performance penalty to page load time, but you can have as many enabled as you like.

Content blocking extensions cannot communicate with each other, so there is no risk of incompatibility between two blockers.

**Comment by demidovakatya** [comment]
Thanks!
