### ISSUE TITLE
Ka-Block 2.5 not available through safari-extensions.apple.com

### ISSUE THREAD

**Issue by kommen** [dgraham/Ka-Block#28]
I can download 2.5 in the Releases section here on github, but I'd rather point friends and family to https://safari-extensions.apple.com for downloading it.

Any chance to make 2.5 available there?

**Comment by dgraham** [comment]
I'll try resubmitting it to Apple. It's been a couple months with no reply to the previous submission. I know it's frustrating.

**Comment by kommen** [comment]
@dgraham thanks!

**Comment by dgraham** [comment]
The response to the latest 2.5 version update was really fast, and it's in the official gallery now. It's even a [featured extension](https://twitter.com/davidgraham/status/690976374207557632)!

**Comment by kommen** [comment]
:tada: :+1:
