### ISSUE TITLE
installation issue with ka-block from apple safari extensions gallery 

### ISSUE THREAD

**Issue by catbot1** [dgraham/Ka-Block#31]
The gallery shows it as installed but I can't find it.  It doesn't show up in extensions list on Macbook.  Just attempting this today.  Any help is much appreciated as this is my first use of an extension on new mac!
Thanks!

**Comment by dgraham** [comment]
I've seen extension installation require a Safari quit and restart for it to appear in the extension preferences panel.

As a last resort, you can install the [latest release](https://github.com/dgraham/Ka-Block/releases/latest) without using the gallery. That will get it installed, but it won't update automatically. It's most convenient to install from the official gallery.

**Comment by catbot1** [comment]
I re-booted computer and that worked!  Thanks for quick response!
