### ISSUE TITLE
Is it possible to install Ka-Block on 32-bit iDevices?

### ISSUE THREAD

**Issue by jan-kleks** [dgraham/Ka-Block#32]
I think I've read somewhere that one can install content blockers on 32-bit iDevices using Xcode. Is this true? How to achieve this? On which devices this method would work?

**Comment by dgraham** [comment]
Content blocking is supported only on 64-bit processors. See #12 for more discussion.

**Comment by jan-kleks** [comment]
Okay, I've found some more info about the Xcode method. It seems to work, at least for some users: https://github.com/krishkumar/BlockParty/issues/14
