### ISSUE TITLE
Include Prebake Filter list

### ISSUE THREAD

**Issue by Phosphor303** [dgraham/Ka-Block#34]
Hi. Do you regard the filter list from http://prebake.eu? If not, consider this a feature request. Thanks!

**Comment by dgraham** [comment]
Thanks for the link. I didn't know about this block list for bothersome cookie notices.

Ka-Block! is focused on maintaining privacy and performance by blocking ads, and while cookie warnings are annoying, they don't track behavior across the web. I think we could add this list if we also added a preferences feature to toggle it. Closing for now.
