### ISSUE TITLE
wired.com replaces content with page demanding whitelisting

### ISSUE THREAD

**Issue by mjgardner** [dgraham/Ka-Block#42]
Eg., http://www.wired.com/2016/08/open-source-won-now/

It makes it impossible to browse the site with Ka-Block.

**Comment by bumblebritches57** [comment]
The problem with this, is that's Wired's own html, and it belongs to a div id, and the author only wants to ban entire domains, not individual divs (IIRC)

**Comment by dgraham** [comment]
Sites that prevent visitors from using a content blocker can be viewed by long-pressing on the 
reload button in Safari and selecting `Reload without Content Blockers`.

The filter list is intended to block third-party domains that collect information on visitors to build a unique profile across websites. First-party content, like that served directly from wired.com, isn't blocked.
