### ISSUE TITLE
Cannot log into the Wall Street Journal Site

### ISSUE THREAD

**Issue by judismith** [dgraham/Ka-Block#47]
When Kablock is active I cannot log into the WJS site at id.wsj.com or any other place that their login appears. When I disable Kablock I can log in.

**Comment by hnic0las** [comment]
Hi,
Do you login with username/password or with social networks?

**Comment by judismith** [comment]
Sorry for missing this. I log in with user name and password.

**Comment by sterlingpetersen** [comment]
I've no problem logging into the WSJ with WSJ credentials. I can't comment on using the social media routes.

**Comment by dgraham** [comment]
It sounds like this may be fixed. If not, there are a couple other options.

1. Click and hold Safari's Refresh button and select Reload Without Content Blockers.
2. Open Preferences > Websites > Content Blockers and disable blocking on this domain.
