### ISSUE TITLE
Release Ka-Block 1.6

### ISSUE THREAD

**Issue by josh** [dgraham/Ka-Block#5]
Hey @dgraham!

Any objections to pushing out the latest as 1.6 (or 2.0, whatever's next)?

I'm not sure when the new rules going into place, but it seems like some changes are being made to the Safari Extension publishing process. Do you think theres anything else that needs to be done to prepare for this?

> In early fall, the new Safari Extensions Gallery for OS X El Capitan will go live. This gallery will be the safest and most reliable place for users to download Safari Extensions, as all extensions will be signed and hosted by Apple to ensure that they are safe to install. All updates to your existing extensions must be submitted to the new gallery.

https://developer.apple.com/safari/extensions/

**Comment by dgraham** [comment]
I went with [2.0](https://github.com/dgraham/Ka-Block/releases/tag/v2.0) because it's a big change to the block list format and supports a new API in Safari 9.

**Comment by josh** [comment]
:grinning:
