### ISSUE TITLE
Hiding youtube ad overlay and ad markers in progress bar

### ISSUE THREAD

**Issue by olbura** [dgraham/Ka-Block#53]
Please, add this rule in order to hide youtube ad overlay and progress bar markers. tnx!

<img width="637" alt="ytp-ad" src="https://cloud.githubusercontent.com/assets/4757856/20179236/587cc102-a755-11e6-85bc-ec86112601df.png">

```
{
    "trigger": {
      "url-filter": "^https?:/+([^/:]+\\.)youtube\\.com[:/]",
      "load-type": [
        "third-party",
        "first-party"
      ]
    },
    "action": {
      "type": "css-display-none",
      "selector": ".ytp-ad-progress-list, .video-ads, .ytp-ad-persistent-progress-bar-container"
    }
  }
```

**Comment by hnic0las** [comment]
I'll test this and add it in my existing pull-request #50

**Comment by dgraham** [comment]
We usually only block domains, rather than CSS selectors, because sites change their selectors frequently, which means more frequent updates to the content blocking filter. I might reevaluate this one in the future if the selectors are stable.
