### ISSUE TITLE
Moatads Subdomains

### ISSUE THREAD

**Issue by bumblebritches57** [dgraham/Ka-Block#54]
Moatads has started? using Subdomains, the page I'm on now loads ads from z.moatads.com, but I'm sure there are others, or soon will be.

**Comment by dgraham** [comment]
Subdomains are [currently blocked](https://github.com/dgraham/Ka-Block/blob/master/Ka-Block.safariextension/filters.json#L2631). If there is an example site that loads assets from this domain, I can take a look.

**Comment by bumblebritches57** [comment]
Heatst.com is where I saw that ad.

**Comment by dgraham** [comment]
I tested the site with the content blocker extension disabled and tracking scripts do load from the subdomain. The scripts are blocked correctly with Ka-Block! enabled in Settings > Safari > Content Blockers.

**Comment by bumblebritches57** [comment]
I'm on Mac, not iOS.

**Comment by dgraham** [comment]
You might double check that the extension is enabled in Safari > Preferences > Extensions on macOS.
