### ISSUE TITLE
Macworld.com videos unplayable

### ISSUE THREAD

**Issue by sxflynn** [dgraham/Ka-Block#55]
If you go to http://www.macworld.com and scroll down to the videos, with Ka-Block enabled I am unable to click on the videos and play them.

**Comment by dgraham** [comment]
Related to `useForcedLinkTracking`:

- https://adblockplus.org/blog/links-not-working-on-a-website-you-can-fix-that
- https://gist.github.com/normanzb/2903e972057bc5d69281
- https://forums.adobe.com/message/5152380#5152380
