### ISSUE TITLE
Kablock doesn't block 

### ISSUE THREAD

**Issue by Machiavel68000** [dgraham/Ka-Block#57]
Hello, 
I use Kablock and I don't understand something. Kablock doesn't block ads on a lot of website. 
I give examples where ads aren't blocking. ( https://www.t411.al / youtube.com / http://www.allocine.fr). 
Is it normal ? 
Thanks for the jobs.

**Comment by dgraham** [comment]
Blocking ad scripts on YouTube prevents the videos from playing so it's disabled. I added filter rules for the other two sites.
