### ISSUE TITLE
Does not block ad on Yahoo Mail

### ISSUE THREAD

**Issue by ChristianSiegert** [dgraham/Ka-Block#63]
Ads are not blocked on https://login.yahoo.com/?.src=fp&.intl=de&.lang=de-DE&.done=https%3a//mail.yahoo.com.

**Comment by dgraham** [comment]
I don't see any third-party ads on the sign in page or the inbox. If you see an advertising domain in Safari's web inspector Network or Resource tools, I can add it to the block list.
