### ISSUE TITLE
Resolve Auto Layout Localization warning

### ISSUE THREAD

**Issue by josh** [dgraham/Ka-Block#66]
As of 9a7bc1e6e58897b80858b8ca55f8973f4275d022 , Xcode 9 warns about an Auto Layout constraint issue in the `Main.storyboard`.

<img width="270" alt="screen shot 2017-09-18 at 10 33 30 am" src="https://user-images.githubusercontent.com/137/30526863-de70714e-9c5c-11e7-857c-46ca664deea3.png">

**Comment by dgraham** [comment]
Fixed in 349b2fa.
