### ISSUE TITLE
Can't install properly on High Sierra

### ISSUE THREAD

**Issue by dingzh** [dgraham/Ka-Block#70]
I tried downloading from the extension gallery and from GitHub, and clicked trust. But Safari shows warning that Ka-blocks does not have permission to read or transmit content from any webpages.
<img width="888" alt="screen shot 2017-10-09 at 21 35 49" src="https://user-images.githubusercontent.com/15306971/31340782-d85d08e2-ad39-11e7-9aab-adca918188f3.png">

**Comment by dgraham** [comment]
This is actually a feature! The extension intentionally does not request permission to read webpages as you view them. It only provides a block list to Safari and the browser does the rest.
