### ISSUE TITLE
Block adwords

### ISSUE THREAD

**Issue by fulldecent** [dgraham/Ka-Block#87]
Please consider to block Google AdWords.

At a minimum, disable loading the interstitial that loads between when you click an ad and when you get to the advertised page.

**Comment by dgraham** [comment]
Google ads are blocked on domains other than google.com to prevent cross-site behavioral tracking. On Google domains they are first-party content and are allowed to load.

**Comment by fulldecent** [comment]
Note to self: resolved by switching to Duck Duck Go. Life is better now. Also DDG allows you to disable ads.
