### ISSUE TITLE
Blocking my banks website view of transactions.

### ISSUE THREAD

**Issue by jmmoody** [dgraham/Ka-Block#93]
My Banks web site's transaction view will not display when this extension is active 
https://webaccess.americafirst.com.   This is 100% repeatable by turning on and off the extension and refreshing the page.

**Comment by sterlingpetersen** [comment]
I can confirm this. I'm guessing it has something to do with AFCU's use of Google Analytics and how their website is loaded. It appears if the Google Analytics script fails to load, it causes the transaction view to subsequently fail also.

You can turn off content blockers for specific pages under Websites -> Content Blockers and then selecting "Off", which is what I ultimately ended up doing.

Not sure there is anything here for Ka-Block to do—the page is designed in such a manner as to fail if an external tracking script isn't loaded.

**Comment by dgraham** [comment]
Good suggestion for disabling the content blocker in Safari's settings for this site.

Sites designed in this way will also fail if the network request for the tracking script fails. Relying on third-party site uptime is a risky dependency regardless of content blocker extensions.
